MODEL:
  BACKBONE:
    DEPTH: 101x
    WITH_IBN: True
    PRETRAIN: True
    PRETRAIN_PATH: "BoT-SORT/pretrained/msmt_sbs_R101-ibn.pth"
DATASETS:
  NAMES: ("MOT20",)
  TESTS: ("MOT20",)
OUTPUT_DIR: logs/mot20/sbs_R101-ibn